# Generated by Django 3.0.7 on 2021-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20210317_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='foodcartapp.OrderPosition', to='foodcartapp.Product'),
        ),
    ]
