# Generated by Django 3.0.7 on 2021-03-30 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderposition',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AddField(
            model_name='orderposition',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_position', to='foodcartapp.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
