# Generated by Django 3.0.7 on 2021-03-30 14:13

from django.db import migrations

def set_current_price(apps, schema_editor):
    ProductPosition = apps.get_model('foodcartapp', 'OrderPosition')

    for position in ProductPosition.objects.all():
        position.current_price = position.product.price
        position.save()

def backward(apps, schema_editor):
    ProductPosition = apps.get_model('foodcartapp', 'OrderPosition')

    for position in ProductPosition.objects.all():
        position.current_price = None
        position.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20210330_1345'),
    ]

    operations = [
        migrations.RunPython(set_current_price, backward)
    ]
