# Generated by Django 3.0.7 on 2021-03-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20210330_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('P', 'В работе'), ('C', 'Выполнен')], default='N', max_length=2, verbose_name='Статус'),
        ),
    ]
