# Generated by Django 3.0.7 on 2021-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время доставки'),
        ),
    ]
