# Generated by Django 3.0.7 on 2021-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='orders', to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
    ]
