# Generated by Django 3.0.7 on 2021-04-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20210419_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
    ]
