# Generated by Django 3.0.7 on 2021-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20210419_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('C', 'Наличными при доставке'), ('O', 'Картой онлайн')], max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
