# Generated by Django 3.0.7 on 2021-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20210419_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
    ]
